name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/poe-server:latest

    - name: Install Nomad CLI
      run: |
        apt update -yq && apt install -yq curl gnupg gettext-base
        curl -L https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        export $( cat /etc/lsb-release | grep DISTRIB_CODENAME ); echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com ${DISTRIB_CODENAME} main" | tee /etc/apt/sources.list.d/hashicorp.list
        apt update -yq && apt install -yq nomad

    - name: Deploy to Nomad
      run: |
        mkdir -p .secrets
        base64 -d << "{{ secrets.NOMAD_CACERT }}" > .secrets/nomad-ca.pem
        base64 -d << "{{ secrets.NOMAD_CLIENT_CERT }}" > .secrets/nomad-client.pem
        base64 -d << "{{ secrets.NOMAD_CLIENT_KEY }}" > .secrets/nomad-client-key.pem

        envsubst < server.nomad > server.hcl
        nomad job run server.hcl
      env:
        NOMAD_CACERT: .secrets/nomad-ca.pem
        NOMAD_CLIENT_CERT: .secrets/nomad-client.pem
        NOMAD_CLIENT_KEY: .secrets/nomad-client-key.pem
        NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        POE_COOKIES: ${{ secrets.POE_COOKIES }}